# Generated by Django 4.2.10 on 2024-02-29 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_comment_options_remove_comment_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
    ]
