# Generated by Django 5.0.3 on 2024-03-13 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_technology_remove_project_technology_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
