# Generated by Django 5.0.3 on 2024-03-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0010_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contribution_role",
            field=models.TextField(
                blank=True, help_text="Your role/contribution in the project"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Mark as featured to highlight on the portfolio",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("archived", "Archived"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.CharField(
                default="Not Specified",
                help_text="List technologies separated by commas",
                max_length=200,
            ),
        ),
    ]
