# Generated by Django 5.0.3 on 2024-03-22 18:57

import portfolio.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_projectimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=models.ImageField(
                upload_to="project_images/",
                validators=[portfolio.validators.validate_file_size],
            ),
        ),
    ]
