# Generated by Django 5.0.3 on 2024-03-22 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0013_alter_projectimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
    ]
